### ISSUE TITLE
how is the shoulder joint placement defined?

### ISSUE THREAD

**Issue by ghost** [intel/riggingtools#12]
I've noticed in earlier versions of the code I get slight differences in shoulder joint 3D locations. Are those based on a calculated "clavicle length" from the data or a constant value?. 
Here is an image showing this variability for the same input data
<img width="232" alt="Screen Shot 2020-12-06 at 9 25 44 PM" src="https://user-images.githubusercontent.com/36975665/101946984-99721d00-3ba4-11eb-96d9-3ec025b81105.png">

**Comment by johnhe4** [comment]
I'll take a look at this early next week. I think it will either be straightforward to fix, or is already correct and the old method is incorrect.

**Comment by johnhe4** [comment]
Resolved, merged to main
