### ISSUE TITLE
skeleton scale is off

### ISSUE THREAD

**Issue by ghost** [intel/riggingtools#7]
I may have uncovered a bug starting from a patch that was merged to master of Sept 21 2020 but I have not been able to identify the root cause. 
The skeleton height from the input data is generally in the 1.8 meter range, since that patch on Sept 21, for the same input data, the skeleton height seems to be shrink (normalized) to something in the 1.5m range. 
This observation is with the -u 0.1 to convert from decimeters to meters and using rig2blender for visualization.
Any inputs to where the issue might have been introduced or how to diagnose?

**Comment by johnhe4** [comment]
Looking into it

**Comment by johnhe4** [comment]
@rbruga I could not reproduce using the included mpii data, at least not in kp2rig (haven't tried blender yet). I printed the final rig bone lengths for `player_7` with a commit from Sept 15th and the latest (+ smoothing bug fix on patch-1), the values look the same to me.

commit 9e1005604c898da3e73a22db53ae0f5685f16fde (Sept 15th):
0.116002
0.431817
0.441238
0.161949
0.0539828
0.421714
0.443752
0.162871
0.0542903
0.110468
0.115331
0.106672
0.281204
0.234806
0.149422
0.278238
0.238136
0.151541
0.0896782
0.292262

Latest (patch-1):
0.116002
0.431817
0.441238
0.161949
0.0539828
0.421714
0.443752
0.162871
0.0542903
0.110468
0.115331
0.106672
0.281204
0.234806
0.149422
0.278238
0.238136
0.151541
0.0896782
0.292262

What is your process for checking height in blender?

**Comment by ghost** [comment]
@johnhe4  thanks for the quick response! :) might be on the blender side.. I am checking heights in with blender 2.8 with the measuring tool in the GUI

**Comment by ghost** [comment]
@johnhe4 attaching some visualization of the same data before and after the issue. if you look carefully looks like hips joints align well in both datasets but the latest rigs have limb sizes that are too small.
<img width="338" alt="Screen Shot 2020-12-01 at 2 11 23 PM" src="https://user-images.githubusercontent.com/36975665/100803041-50b9a780-33df-11eb-99b2-6de99802e9e9.png">
<img width="338" alt="Screen Shot 2020-12-01 at 2 10 59 PM" src="https://user-images.githubusercontent.com/36975665/100803045-52836b00-33df-11eb-92fc-239433bf86b0.png">
<img width="319" alt="Screen Shot 2020-12-01 at 2 09 22 PM" src="https://user-images.githubusercontent.com/36975665/100803047-531c0180-33df-11eb-862b-44734cddb353.png">

**Comment by johnhe4** [comment]
Helpful pics @rbruga, thx. I looked at the blender code and it is using the scale of the default humanoid, not the bone lengths passed in. Let me work on fixing this by applying the proper bone lengths IF they are present, since bone lengths are not required.

**Comment by ghost** [comment]
@johnhe4 thank you for quick response! i've tested the patch and the limb lengths look correct now. Related or maybe unrelated to this issue... the 2D location of the skeletons in the scene I understand is driven by the absolute coordinates of the root joint at the pelvis. Is there a scale or transformation between the pelvis coordinates in the skeleton input data files and the corresponding pelvis 3D location in blender scene?

**Comment by johnhe4** [comment]
No, the only modification to the location should be the unit normalizer (0.1 in your case). In order to get Blender to look correct, there are axis transformations (Z becomes Y, X is negated, etc.)

**Comment by ghost** [comment]
@johnhe4 I've merged skeletons before and after fix and I can visualize the scale issue is resolved. Thanks! I've also merged 2 versions of the same skeleton (old one generated in Sept) with the one generated with this latest patch and it seems that this latest one has "shorter clavicles". Are the shoulder joints placed at a constant clavicle distance or what explains this distance? is this clavicle length calculated from the data?
<img width="232" alt="Screen Shot 2020-12-06 at 9 25 44 PM" src="https://user-images.githubusercontent.com/36975665/101313519-2581ee80-380b-11eb-9403-ccf273bb4cc3.png">

**Comment by ghost** [comment]
closing issue since last post in unrelated from main topic.

**Comment by johnhe4** [comment]
Please open a new issue for clavicle and I'll take a look, I'll bet it's similar to the bone length issue
